trigger:
- master

pr:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'wwt-website.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: PowerShell@2
  displayName: 'Update version'
  name: updateVersion
  inputs:
    targetType: 'inline'
    script: |
      dotnet tool install --global GitVersion.Tool --version 5.1.2      
      dotnet gitversion /output buildserver /nofetch

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'src/WWTMVC5'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install -g bower'

- task: PowerShell@2
  inputs:
    filePath: 'init.ps1'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:PrecompileBeforePublish=true /p:EnableUpdateable=false /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)/website"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Create tool package
  inputs:
    command: 'pack'
    packagesToPack: 'tools/PlateManager/PlateManager.csproj'
    packDirectory: '$(Build.ArtifactStagingDirectory)/tools'
    includesymbols: true
    includesource: true
    versioningScheme: 'off'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\WWT.*.Tests.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(build.artifactStagingDirectory)/website'
    artifact: 'website'
    publishLocation: 'pipeline'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(build.artifactStagingDirectory)/tools'
    artifact: 'tools'
    publishLocation: 'pipeline'

- task: DotNetCoreCLI@2
  displayName: Push tools to feed
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/tools/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '5b8413f0-309f-4655-933b-c3b9516cd60f/cec2a436-ea5b-41d3-a4d4-8f2380a4c6a9'
  condition: ne(variables['Build.Reason'], 'PullRequest')